repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        name: unified code formating 
        language_version: python3.8

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: flake8

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.782'  
    hooks:
    -   id: mypy 

-   repo: local
    hooks:
    -   id: tests
        name: run tests
        entry: pytest -v
        language: system
        types: [python]
        stages: [push] 