version: "3"
services:
  scraper:
    build: .
    ports:
      - "9111:9111"
    depends_on:
      - database
  database:
    build: ./postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: vebeg 
      POSTGRES_USER: vebeg
      POSTGRES_DB: vebeg
   # volumes:
  #   - vebeg_postgress:/var/lib/postgresql/data